# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import main.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', main.models.UserAccountManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='unique verification UUID'),
        ),
    ]
